spring:
  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  mail:
    host: smtp.gmail.com   # 사용하려는 메일 서버
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  config:
    import: "classpath:application-secret.yml"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true  # SQL을 이쁘게 포맷팅
        default_batch_fetch_size: 50 # 연관관계(LAZY)에서 N+1 문제를 줄이기 위해 한 번에 50개씩 IN 쿼리로 묶어서 가져오게 하는 옵션
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: debug # 실행되는 SQL 문장 자체를 로깅
    org.hibernate.orm.jdbc.bind: trace # SQL 안의 바인딩 값(?, ?, ?)에 들어가는 실제 파라미터를 출력

springdoc:
  swagger-ui:
    path: /api-docs-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: list

  api-docs:
    path: /my-api

discodeit:
  storage:
    type: local
    local:
      root-path: A:/myCodes/codit/sprint/storage