spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234

  mail:
    username: greylife5451@gmail.com
    password: hgedemyzrahtzkys

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

discodeit:
  storage:
    type: local
    local:
      root-path: ./storage
  admin:
    email: "principle950@naver.com"
    nickname: "principle950"
    password: "qwer123$"

logging:
  level:
    root: info
    com.sprint.mission.discodeit: debug
    org.hibernate.orm.jdbc.bind: info
    rg.springframework.security: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true