server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234

  mail:
    username: ${MAIL_ID}
    password: ${MAIL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    sql:
      init:
        mode: never
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}

discodeit:
  storage:
    type: s3
    s3:
      path: binary

logging:
  level:
    root: INFO
    com.sprint.mission.discodeit: INFO

management:
  endpoint:
    health:
      show-details: never
      show-components: when_authorized
      probes:
        enabled: true
  info:
    env:
      enabled: false