spring:
  config:
    import: optional:dotenv:./.env

  profiles:
    active:
      - dev

  application:
    name: discodeit

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50

springdoc:
  swagger-ui:
    path: /api-docs-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: list

  api-docs:
    path: /my-api

info:
  app:
    name: discodeit
    version: 1.0.0
    encoding: UTF-8
    java-version: 17
    spring-version: 3.5.9